### PR TITLE
Refactored Dockerfile

### PR DESCRIPTION
**Pull request by danielwagn3r**
Docker image buildable without any implicit dependencies (from Docker host)
Switched to Ubuntu LTS base image
Updated prerequisites according to https://imapsync.lamiral.info/INSTALL.d/INSTALL.Ubuntu.txt

### CODE REVIEW

**Comment by danielwagn3r** [comment]
With this a Docker buildx multi-arch build is possible, e.g. like this:
```
docker buildx create --use
docker buildx build --platform linux/amd64,linux/arm64,linux/arm,linux/s390x -t imapsync:1.998 -t imapsync:latest -f INSTALL.d/Dockerfile .
```

**Comment by gilleslamiral** [comment]
It will be erased the next time I publish imapsync since I work on Debian.

**Comment by danielwagn3r** [comment]
Cool, I've reverted the Ubuntu change anyway already. I'm working on a GitHub Action for automated releases, i.e. image build and push to Docker Hub.

**Comment by gilleslamiral** [comment]
Daniel you wrote:
> With this a Docker buildx multi-arch build is possible, e.g. like this:
> 
> ```
> docker buildx create --use
> docker buildx build --platform linux/amd64,linux/arm64,linux/arm,linux/s390x -t imapsync:1.998 -t imapsync:latest -f INSTALL.d/Dockerfile .
> ```

I thank you very much for this command, building a multi-arch image is on my TODO list. I also work on Debian to build the Docker image. My current issue is that "Docker Buildx is included in Docker 19.03" (https://docs.docker.com/buildx/working-with-buildx/) but on my Debian 10 I have Docker  18.09.1 

```
$ docker version
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.6
 Git commit:        4c52b90
 Built:             Sun, 14 Jun 2020 22:12:29 +0200
 OS/Arch:           linux/amd64
 Experimental:      false
```

I notice that BuildX is considered experimental by Docker. Anyway if it works well with imapsync then I'm very ok to use it.

**Comment by danielwagn3r** [comment]
I see, I've never used distro shipped packages of docker (except for Arch Linux) as there have always been problems and upstream packages were always more current. The automated build proposed in #259 might be step forward as well.

**Pull request merged**
