### PR TITLE
Add libauthen-ntlm-perl as a dependency in INSTALL notes.

### PR DESCRIPTION
**Pull request by stylesen**
Dependency for Debian / Ubuntu installation.

### CODE REVIEW

**Comment by gilleslamiral** [comment]
Hi Senthil,

It will be fixed on next github update.

Since now there is
http://imapsync.lamiral.info/INSTALL.d/
http://imapsync.lamiral.info/INSTALL.d/INSTALL.Ubuntu.txt

Le 04/05/2015 15:20, Senthil Kumaran a écrit :
> stylesen wants to merge 1 commit into imapsync:master from stylesen:master:
>
> Dependency for Debian / Ubuntu installation.
>
> ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
> https://github.com/imapsync/imapsync/pull/29
>
>
>         Commit Summary
>
>   * Add libauthen-ntlm-perl as a dependency in INSTALL notes.
>
>
>         File Changes
>
>   * *M* INSTALL <https://github.com/imapsync/imapsync/pull/29/files#diff-0> (3)
>
>
>         Patch Links:
>
>   * https://github.com/imapsync/imapsync/pull/29.patch
>   * https://github.com/imapsync/imapsync/pull/29.diff
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/imapsync/imapsync/pull/29>.
>

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by stylesen** [comment]
Hi Gilles,

You feel this pull request is appropriate to fix the current INSTALL doc in the git tree? Or you have plans to bring in contents from http://imapsync.lamiral.info/INSTALL.d ?

Thank You.

**Comment by gilleslamiral** [comment]
I just said it will be fixed on next github update from upstream imapsync.
So it's useless to spend time on this now.


Le 04/05/2015 15:49, Senthil Kumaran a écrit :
> Hi Gilles,
>
> You feel this pull request is appropriate to fix the current INSTALL doc in the git tree? Or you have plans to bring in contents from http://imapsync.lamiral.info/INSTALL.d ?
>
> Thank You.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/imapsync/imapsync/pull/29#issuecomment-98709107>.
>

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by stylesen** [comment]
Based on Gilles's comment closing this pull request.

**Pull request closed without merging**
