### PR TITLE
Fix for using user's perl instead of system perl

### PR DESCRIPTION
**Pull request by tony-o**
Helpful for people using plenv or perl brew.

### CODE REVIEW

**Comment by gilleslamiral** [comment]
Dear Tony,

What happens if env does not exist or is elsewhere?
Same issue as perl itself in the shebang.
So I won't apply this patch upstream.
You can also try directly the following shebang, it works sometimes:

#!perl


To the rescue, on the command line:

   perl imapsync ...

or

   /path/to/myperl imapsync ...

will allow to use any perl wanted.

Other solutions are writing a small shell script or a shell alias or a shell function
doing the same thing.

Le 01/04/2015 20:31, tony-o a écrit :
> Helpful for people using plenv or perl brew.
>
> ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
> https://github.com/imapsync/imapsync/pull/28


-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by tony-o** [comment]
That's fine, I'll keep a local copy that plays nicely with local users' perl


-
Tony O'Dell | BestXperts
(916) 220-9336

**Comment by gilleslamiral** [comment]
Thanks Tony, good reaction!
I'm still open to patches for the next thousands lines of imapsync.

Le 01/04/2015 21:51, tony-o a écrit :
> That's fine, I'll keep a local copy that plays nicely with local users' perl
>

-- 
Au revoir,                             09 51 84 42 42
Gilles Lamiral. France, Baulon (35580) 06 20 79 76 06

**Comment by tony-o** [comment]
Haha, thanks.


Read it briefly to see if it could fork on each folder - may get a PR sometime

**Pull request closed without merging**
